version: '2'

services:

  geoserver:
    image: geonode/geoserver
    build:
      context: .
      args:
        - DOCKER_HOST
        - PUBLIC_PORT=80
    ports:
      - "8080:8080"
    #volumes:
      #- /srv/docker/geoserver/geoserver:/geoserver_data
    environment:
      - DOCKER_HOST
      - PUBLIC_PORT=80
      - DOCKER_HOST_IP
      - DJANGO_URL=http://localhost/
  
